service: haasivut-backend

plugins:
  - serverless-webpack

custom:
  stage: ${opt:stage, self:provider.stage}
  registrationsTable: registrations-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs12.x
  stage: development
  region: eu-central-1
  memorySize: 256
  timeout: 10
  profile: personal
  apiKeys:
    - value: 3oTVWKxXWGPdHr7bqCyYmImIuCCkjjZuU1rKRaSWekVwMAp0U0mkI2NKgxzDPFKs
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource:
        - "arn:aws:ses:*:*:*"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ RegistrationsTable, Arn ]
  environment:
    ENVIRONMENT: ${self:custom.stage}
    REGISTRATIONS_TABLE: ${self:custom.registrationsTable}

package:
  individually: true

functions:
  list-registrations:
    handler: handlers/list-registrations/index.handler
    events:
      - http:
          method: GET
          path: list-registrations
          private: true
  registrations:
    handler: handlers/registrations/index.handler
    events:
      - http:
          method: POST
          path: register
          cors: true

resources:
  Resources:
    RegistrationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.registrationsTable}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
