service: haasivut-backend

plugins:
  - serverless-webpack

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  stage: development
  region: eu-central-1
  memorySize: 128
  timeout: 10
  environment:
    ENVIRONMENT: ${self:custom.stage}

package:
  individually: true

functions:
  registrations:
    handler: handlers/registrations/index.handler
    events:
      - http:
          method: POST
          path: register
          cors: true